var UIStringTable = {
    '##WIRELESS_PLAYBACK_DEVICE_TYPE##': 'AirPlay',
    '##WIRELESS_PLAYBACK_DEVICE_NAME##': 'Este vídeo está sendo reproduzido em “##DEVICE_NAME##”.',

    '##TVOUT_DEVICE_TYPE##': 'TV Conectada',
    '##TVOUT_DEVICE_NAME##': 'Este vídeo está sendo reproduzido na TV.',

    'Aborted': 'Anulado',
    'Audio': 'Áudio',
    'Audio Playback': 'Reprodução de Áudio',
    'Captions': 'Legendas',
    'Choose Wireless Display': 'Escolher Tela sem Fio',
    'Display Full Screen': 'Exibir Tela Cheia',
    'Display Picture in Picture': 'Exibir PIP',
    'Duration': 'Duração',
    'Elapsed': 'Decorrido',
    'Error': 'Erro',
    'Exit Full Screen': 'Sair da Tela Cheia',
    'Fast Forward': 'Avançar Rapidamente',
    'Live Broadcast': 'Transmissão ao Vivo',
    'Loading': 'Carregando',
    'Maximum Volume': 'Volume Máximo',
    'Minimum Volume': 'Volume Mínimo',
    'Mute': 'Mudo',
    'Pause': 'Pausa',
    'Play': 'Reproduzir',
    'Remaining': 'Restante',
    'Rewind': 'Retroceder',
    'Rewind ##sec## Seconds': 'Retroceder ##sec## Segundos',
    'Show Controls': 'Mostrar Controles',
    'Stalled': 'Parado',
    'Start Playback': 'Iniciar Reprodução',
    'Subtitles': 'Legendas',
    'Suspended': 'Interrompido',
    'This video is playing in Picture in Picture': 'Este vídeo está sendo reproduzido em PIP',
    'Unmute': 'Ativar Som',
    'Video Playback': 'Reprodução de Vídeo',
    'Video Playback Placeholder': 'Marcador de Posição de Reprodução de Vídeo',
    'Volume': 'Volume',
    'Waiting': 'Esperando'
};