var UIStringTable = {
    '##WIRELESS_PLAYBACK_DEVICE_TYPE##': 'AirPlay',
    '##WIRELESS_PLAYBACK_DEVICE_NAME##': 'Video ini diputar di “##DEVICE_NAME##”.',

    '##TVOUT_DEVICE_TYPE##': 'TV Tersambung',
    '##TVOUT_DEVICE_NAME##': 'Video ini diputar di TV.',

    'Aborted': 'Digagalkan',
    'Audio': 'Audio',
    'Audio Playback': 'Pemutaran Audio',
    'Captions': 'Teks',
    'Choose Wireless Display': 'Pilih Layar Nirkabel',
    'Display Full Screen': 'Tampilkan Layar Penuh',
    'Display Picture in Picture': 'Tampilkan Gambar dalam Gambar',
    'Duration': 'Durasi',
    'Elapsed': 'Berlalu',
    'Error': 'Kesalahan',
    'Exit Full Screen': 'Keluar dari Layar Penuh',
    'Fast Forward': 'Percepat Maju',
    'Live Broadcast': 'Siaran Langsung',
    'Loading': 'Memuat',
    'Maximum Volume': 'Volume Maksimum',
    'Minimum Volume': 'Volume Minimum',
    'Mute': 'Bisukan',
    'Pause': 'Jeda',
    'Play': 'Mainkan',
    'Remaining': 'Tersisa',
    'Rewind': 'Putar balik',
    'Rewind ##sec## Seconds': 'Putar balik ##sec## Detik',
    'Show Controls': 'Tampilkan Kontrol',
    'Stalled': 'Berhenti Berfungsi',
    'Start Playback': 'Mulai Pemutaran',
    'Subtitles': 'Subjudul',
    'Suspended': 'Ditangguhkan',
    'This video is playing in Picture in Picture': 'Video ini diputar di Gambar dalam Gambar',
    'Unmute': 'Bunyikan',
    'Video Playback': 'Pemutaran Video',
    'Video Playback Placeholder': 'Placeholder Pemutaran Video',
    'Volume': 'Volume',
    'Waiting': 'Menunggu'
};