var UIStringTable = {
    '##WIRELESS_PLAYBACK_DEVICE_TYPE##': 'AirPlay',
    '##WIRELESS_PLAYBACK_DEVICE_NAME##': 'Ovaj videozapis reproducira se na uređaju “##DEVICE_NAME##”.',

    '##TVOUT_DEVICE_TYPE##': 'TV je spojen',
    '##TVOUT_DEVICE_NAME##': 'Ovaj videozapis reproducira se na TV-u.',

    'Aborted': 'Prekinuto',
    'Audio': 'Audio',
    'Audio Playback': 'Reprodukcija zvuka',
    'Captions': 'Prošireni titlovi',
    'Choose Wireless Display': 'Odaberite bežični zaslon',
    'Display Full Screen': 'Prikaži preko cijelog zaslona',
    'Display Picture in Picture': 'Prikaži sliku u slici',
    'Duration': 'Trajanje',
    'Elapsed': 'Proteklo',
    'Error': 'Greška',
    'Exit Full Screen': 'Isključi prikaz preko cijelog zaslona',
    'Fast Forward': 'Pretraživanje unaprijed',
    'Live Broadcast': 'Emitiranje uživo',
    'Loading': 'Učitavanje',
    'Maximum Volume': 'Maksimalna glasnoća',
    'Minimum Volume': 'Minimalna glasnoća',
    'Mute': 'Isključi zvuk',
    'Pause': 'Pauza',
    'Play': 'Reproduciraj',
    'Remaining': 'Preostalo',
    'Rewind': 'Pretraživanje unatrag',
    'Rewind ##sec## Seconds': 'Pretraživanje ##sec## s unatrag',
    'Show Controls': 'Prikaži kontrole',
    'Stalled': 'Zastajkuje',
    'Start Playback': 'Pokreni reprodukciju',
    'Subtitles': 'Titlovi',
    'Suspended': 'Zaustavljeno',
    'This video is playing in Picture in Picture': 'Ovaj videozapis se reproducira kao slika u slici',
    'Unmute': 'Uključi zvuk',
    'Video Playback': 'Reprodukcija videozapisa',
    'Video Playback Placeholder': 'Držač mjesta za video reprodukciju',
    'Volume': 'Glasnoća',
    'Waiting': 'Čekanje'
};