var UIStringTable = {
    '##WIRELESS_PLAYBACK_DEVICE_TYPE##': 'AirPlay',
    '##WIRELESS_PLAYBACK_DEVICE_NAME##': 'Este vídeo se está reproduciendo en “##DEVICE_NAME##”.',

    '##TVOUT_DEVICE_TYPE##': 'Televisor conectado',
    '##TVOUT_DEVICE_NAME##': 'Este vídeo se está reproduciendo en el televisor.',

    'Aborted': 'Anulado',
    'Audio': 'Audio',
    'Audio Playback': 'Reproducción de audio',
    'Captions': 'Subtítulos opcionales',
    'Choose Wireless Display': 'Seleccionar pantalla inalámbrica',
    'Display Full Screen': 'Mostrar pantalla completa',
    'Display Picture in Picture': 'Mostrar imagen dentro de imagen',
    'Duration': 'Duración',
    'Elapsed': 'Transcurrido',
    'Error': 'Error',
    'Exit Full Screen': 'Salir de pantalla completa',
    'Fast Forward': 'Avance rápido',
    'Live Broadcast': 'Emisión en vivo',
    'Loading': 'Cargando',
    'Maximum Volume': 'Volumen máximo',
    'Minimum Volume': 'Volumen mínimo',
    'Mute': 'Silenciar',
    'Pause': 'Pausa',
    'Play': 'Reproducir',
    'Remaining': 'Restante',
    'Rewind': 'Retroceso',
    'Rewind ##sec## Seconds': 'Retroceder ##sec## segundos',
    'Show Controls': 'Mostrar controles',
    'Stalled': 'Parado',
    'Start Playback': 'Iniciar reproducción',
    'Subtitles': 'Subtítulos',
    'Suspended': 'Suspendido',
    'This video is playing in Picture in Picture': 'Este vídeo se está reproduciendo en modo de imagen dentro de imagen',
    'Unmute': 'Activar sonido',
    'Video Playback': 'Reproducción de vídeo',
    'Video Playback Placeholder': 'Marcador de posición de reproducción de vídeo',
    'Volume': 'Volumen',
    'Waiting': 'Esperando'
};