var UIStringTable = {
    '##WIRELESS_PLAYBACK_DEVICE_TYPE##': 'AirPlay',
    '##WIRELESS_PLAYBACK_DEVICE_NAME##': 'Denne video afspilles på “##DEVICE_NAME##”.',

    '##TVOUT_DEVICE_TYPE##': 'Tv tilsluttet',
    '##TVOUT_DEVICE_NAME##': 'Denne video afspilles på fjernsynet.',

    'Aborted': 'Afbrudt',
    'Audio': 'Lyd',
    'Audio Playback': 'Afspilning af lyd',
    'Captions': 'Billedtekster',
    'Choose Wireless Display': 'Vælg trådløs skærm',
    'Display Full Screen': 'Vis i fuld skærm',
    'Display Picture in Picture': 'Vis billede i billede',
    'Duration': 'Varighed',
    'Elapsed': 'Forløbet',
    'Error': 'Fejl',
    'Exit Full Screen': 'Afslut fuld skærm',
    'Fast Forward': 'Spol frem',
    'Live Broadcast': 'Direkte udsendelse',
    'Loading': 'Indlæser',
    'Maximum Volume': 'Maksimal lydstyrke',
    'Minimum Volume': 'Minimum lydstyrke',
    'Mute': 'Lydløs',
    'Pause': 'Pause',
    'Play': 'Afspil',
    'Remaining': 'Resterende',
    'Rewind': 'Tilbage',
    'Rewind ##sec## Seconds': 'Spol ##sec## sekunder tilbage',
    'Show Controls': 'Vis kontrolenheder',
    'Stalled': 'Standset',
    'Start Playback': 'Start afspilning',
    'Subtitles': 'Undertekster',
    'Suspended': 'Afbrudt',
    'This video is playing in Picture in Picture': 'Videoen afspilles i formatet billede i billede',
    'Unmute': 'Slå lyd til',
    'Video Playback': 'Afspilning af video',
    'Video Playback Placeholder': 'Afspilningseksempel for video',
    'Volume': 'Lydstyrke',
    'Waiting': 'Venter'
};