var UIStringTable = {
    '##WIRELESS_PLAYBACK_DEVICE_TYPE##': 'AirPlay',
    '##WIRELESS_PLAYBACK_DEVICE_NAME##': 'Toto video sa prehráva na „##DEVICE_NAME##“.',

    '##TVOUT_DEVICE_TYPE##': 'TV pripojené',
    '##TVOUT_DEVICE_NAME##': 'Toto video sa prehráva na TV.',

    'Aborted': 'Prerušené',
    'Audio': 'Audio',
    'Audio Playback': 'Prehrávanie audia',
    'Captions': 'Skryté titulky',
    'Choose Wireless Display': 'Vyberte bezdrôtový displej',
    'Display Full Screen': 'Zobraziť na celej obrazovke',
    'Display Picture in Picture': 'Zobraziť obraz v obraze',
    'Duration': 'Trvanie',
    'Elapsed': 'Uplynulo',
    'Error': 'Chyba',
    'Exit Full Screen': 'Vypnúť zobrazenie na celej obrazovke',
    'Fast Forward': 'Prevíjanie dopredu',
    'Live Broadcast': 'Živé vysielanie',
    'Loading': 'Načítava sa',
    'Maximum Volume': 'Maximálna hlasitosť',
    'Minimum Volume': 'Minimálna hlasitosť',
    'Mute': 'Stíšiť',
    'Pause': 'Pozastaviť',
    'Play': 'Prehrať',
    'Remaining': 'Zostáva',
    'Rewind': 'Prevíjanie dozadu',
    'Rewind ##sec## Seconds': 'Previnúť ##sec## s',
    'Show Controls': 'Zobraziť ovládanie',
    'Stalled': 'Prerušené',
    'Start Playback': 'Spustiť prehrávanie',
    'Subtitles': 'Titulky',
    'Suspended': 'Zastavené',
    'This video is playing in Picture in Picture': 'Video sa prehráva ako obraz v obraze',
    'Unmute': 'Zrušiť stíšenie',
    'Video Playback': 'Prehrávanie videa',
    'Video Playback Placeholder': 'Kontajner pre prehrávanie videa',
    'Volume': 'Hlasitosť',
    'Waiting': 'Čaká'
};