var UIStringTable = {
    '##WIRELESS_PLAYBACK_DEVICE_TYPE##': 'AirPlay',
    '##WIRELESS_PLAYBACK_DEVICE_NAME##': 'Ez a videó a(z) „##DEVICE_NAME##” eszközön játszódik.',

    '##TVOUT_DEVICE_TYPE##': 'Tv csatlakoztatva',
    '##TVOUT_DEVICE_NAME##': 'Ez a videó éppen a tv-n játszódik.',

    'Aborted': 'Megszakítva',
    'Audio': 'Hang',
    'Audio Playback': 'Hanglejátszás',
    'Captions': 'Képfeliratok',
    'Choose Wireless Display': 'Vezeték nélküli kijelző kiválasztása',
    'Display Full Screen': 'Teljesképernyős megjelenítés',
    'Display Picture in Picture': 'Kép a képben megjelenítés',
    'Duration': 'Időtartam',
    'Elapsed': 'Eltelt',
    'Error': 'Hiba',
    'Exit Full Screen': 'Kilépés a teljes képernyős módból',
    'Fast Forward': 'Gyors előretekerés',
    'Live Broadcast': 'Élő adás',
    'Loading': 'Betöltés',
    'Maximum Volume': 'Maximális hangerő',
    'Minimum Volume': 'Minimális hangerő',
    'Mute': 'Némítás',
    'Pause': 'Szüneteltetés',
    'Play': 'Játék',
    'Remaining': 'Hátralévő',
    'Rewind': 'Visszatekerés',
    'Rewind ##sec## Seconds': '##sec## másodperc visszatekerése',
    'Show Controls': 'Vezérlők megjelenítése',
    'Stalled': 'Leállt',
    'Start Playback': 'Lejátszás megkezdése',
    'Subtitles': 'Feliratok',
    'Suspended': 'Felfüggesztve',
    'This video is playing in Picture in Picture': 'Ez a videó kép a képben nézetben van lejátszva',
    'Unmute': 'Némítás feloldása',
    'Video Playback': 'Videó lejátszása',
    'Video Playback Placeholder': 'Videolejátszás helyőrzője',
    'Volume': 'Hangerő',
    'Waiting': 'Várakozás'
};