var UIStringTable = {
    '##WIRELESS_PLAYBACK_DEVICE_TYPE##': 'AirPlay',
    '##WIRELESS_PLAYBACK_DEVICE_NAME##': 'جاري تشغيل هذا الفيديو على "##DEVICE_NAME##".',

    '##TVOUT_DEVICE_TYPE##': 'التلفاز متصل',
    '##TVOUT_DEVICE_NAME##': 'جاري تشغيل هذا الفيديو على التلفاز.',

    'Aborted': 'تم الإيقاف قبل الاكتمال',
    'Audio': 'الصوت',
    'Audio Playback': 'تشغيل الصوت',
    'Captions': 'الشرح المكتوب',
    'Choose Wireless Display': 'اختيار شاشة عرض لاسلكية',
    'Display Full Screen': 'عرض في وضع ملء الشاشة',
    'Display Picture in Picture': 'عرض صورة داخل صورة',
    'Duration': 'المدة',
    'Elapsed': 'منقضي',
    'Error': 'خطأ',
    'Exit Full Screen': 'إنهاء وضع ملء الشاشة',
    'Fast Forward': 'تقديم سريع للأمام',
    'Live Broadcast': 'بث مباشر',
    'Loading': 'تحميل',
    'Maximum Volume': 'الحد الأقصى لمستوى الصوت',
    'Minimum Volume': 'الحد الأدنى لمستوى الصوت',
    'Mute': 'كتم الصوت',
    'Pause': 'إيقاف مؤقت',
    'Play': 'تشغيل',
    'Remaining': 'المتبقي',
    'Rewind': 'إرجاع',
    'Rewind ##sec## Seconds': 'إرجاع ##ثانية## من الثواني',
    'Show Controls': 'إظهار عناصر التحكم',
    'Stalled': 'توقف',
    'Start Playback': 'بدء التشغيل',
    'Subtitles': 'عناوين النص',
    'Suspended': 'معلقة',
    'This video is playing in Picture in Picture': 'جاري تشغيل هذا الفيديو كصورة داخل صورة',
    'Unmute': 'إلغاء كتم الصوت',
    'Video Playback': 'تشغيل الفيديو',
    'Video Playback Placeholder': 'عنصر نائب لإعادة تشغيل الفيديو',
    'Volume': 'مستوى الصوت',
    'Waiting': 'قيد الانتظار'
};