var UIStringTable = {
    '##WIRELESS_PLAYBACK_DEVICE_TYPE##': 'AirPlay',
    '##WIRELESS_PLAYBACK_DEVICE_NAME##': 'Cette vidéo est en lecture sur « ##DEVICE_NAME## ».',

    '##TVOUT_DEVICE_TYPE##': 'Téléviseur connecté',
    '##TVOUT_DEVICE_NAME##': 'Cette vidéo est en lecture sur le téléviseur.',

    'Aborted': 'Interrompue',
    'Audio': 'Audio',
    'Audio Playback': 'Lecture audio',
    'Captions': 'Sous-titres',
    'Choose Wireless Display': 'Choisir un moniteur sans fil',
    'Display Full Screen': 'Afficher en plein écran',
    'Display Picture in Picture': 'Afficher l’image dans l’image',
    'Duration': 'Durée',
    'Elapsed': 'Écoulées',
    'Error': 'Erreur',
    'Exit Full Screen': 'Quitter le mode plein écran',
    'Fast Forward': 'Avance rapide',
    'Live Broadcast': 'Diffusion en direct',
    'Loading': 'Chargement',
    'Maximum Volume': 'Volume maximum',
    'Minimum Volume': 'Volume minimum',
    'Mute': 'Silence',
    'Pause': 'Pause',
    'Play': 'Lire',
    'Remaining': 'Restantes',
    'Rewind': 'Retour rapide',
    'Rewind ##sec## Seconds': 'Rembobiner de ##sec## secondes',
    'Show Controls': 'Afficher les contrôles',
    'Stalled': 'En attente',
    'Start Playback': 'Lancer la lecture',
    'Subtitles': 'Sous-titres',
    'Suspended': 'Suspendu',
    'This video is playing in Picture in Picture': 'La lecture de cette vidéo est en Image dans l’image',
    'Unmute': 'Réactiver le son',
    'Video Playback': 'Lecture vidéo',
    'Video Playback Placeholder': 'Paramètre fictif de la vidéo',
    'Volume': 'Volume',
    'Waiting': 'Attente'
};