var UIStringTable = {
    '##WIRELESS_PLAYBACK_DEVICE_TYPE##': 'AirPlay',
    '##WIRELESS_PLAYBACK_DEVICE_NAME##': 'วิดีโอนี้กำลังเล่นอยู่บน “##DEVICE_NAME##”',

    '##TVOUT_DEVICE_TYPE##': 'ต่อกับทีวีอยู่',
    '##TVOUT_DEVICE_NAME##': 'วิดีโอนี้กำลังเล่นอยู่บนทีวี',

    'Aborted': 'ล้มเลิก',
    'Audio': 'เสียง',
    'Audio Playback': 'เล่นเสียง',
    'Captions': 'คำบรรยายภาพ',
    'Choose Wireless Display': 'เลือกจอภาพไร้สาย',
    'Display Full Screen': 'แสดงเต็มหน้าจอ',
    'Display Picture in Picture': 'แสดงหน้าต่างรูปภาพข้างในรูปภาพ',
    'Duration': 'ระยะเวลา',
    'Elapsed': 'ผ่านไป',
    'Error': 'ข้อผิดพลาด',
    'Exit Full Screen': 'ออกจากเต็มหน้าจอ',
    'Fast Forward': 'เลื่อนอย่างเร็วไปข้างหน้า',
    'Live Broadcast': 'ออกอากาศสด',
    'Loading': 'กำลังโหลด',
    'Maximum Volume': 'ความดังเสียงสูงสุด',
    'Minimum Volume': 'ความดังเสียงต่ำสุด',
    'Mute': 'ปิดเสียง',
    'Pause': 'หยุดพัก',
    'Play': 'เล่น',
    'Remaining': 'เหลืออยู่',
    'Rewind': 'เลื่อนอย่างเร็วไปข้างหลัง',
    'Rewind ##sec## Seconds': 'เลื่อนถอยกลับ ##sec## วินาที',
    'Show Controls': 'แสดงแถบควบคุม',
    'Stalled': 'หยุดลง',
    'Start Playback': 'เริ่มเล่น',
    'Subtitles': 'คำบรรยาย',
    'Suspended': 'ถูกระงับ',
    'This video is playing in Picture in Picture': 'วิดีโอนี้กำลังเล่นอยู่ในหน้าต่างรูปภาพข้างในรูปภาพ',
    'Unmute': 'เลิกปิดเสียง',
    'Video Playback': 'เล่นวิดีโอ',
    'Video Playback Placeholder': 'ที่พักสำหรับเล่นวิดีโอ',
    'Volume': 'ความดังเสียง',
    'Waiting': 'กำลังรอ'
};