var UIStringTable = {
    '##WIRELESS_PLAYBACK_DEVICE_TYPE##': 'AirPlay',
    '##WIRELESS_PLAYBACK_DEVICE_NAME##': 'Deze video wordt afgespeeld op \'##DEVICE_NAME##\'.',

    '##TVOUT_DEVICE_TYPE##': 'Tv-aansluiting',
    '##TVOUT_DEVICE_NAME##': 'Deze video wordt afgespeeld op de tv.',

    'Aborted': 'Afgebroken',
    'Audio': 'Audio',
    'Audio Playback': 'Audio afspelen',
    'Captions': 'Bijschriften',
    'Choose Wireless Display': 'Kies draadloos scherm',
    'Display Full Screen': 'Schermvullende weergave',
    'Display Picture in Picture': 'Geef beeld in beeld weer',
    'Duration': 'Duur',
    'Elapsed': 'Verstreken',
    'Error': 'Fout',
    'Exit Full Screen': 'Schakel schermvullende weergave uit',
    'Fast Forward': 'Spoel vooruit',
    'Live Broadcast': 'Live-uitzending',
    'Loading': 'Laden',
    'Maximum Volume': 'Maximale volume',
    'Minimum Volume': 'Minimale volume',
    'Mute': 'Uit',
    'Pause': 'Pauze',
    'Play': 'Speel af',
    'Remaining': 'Resterend',
    'Rewind': 'Spoel terug',
    'Rewind ##sec## Seconds': 'Spoel ##sec## seconden terug',
    'Show Controls': 'Toon regelaars',
    'Stalled': 'Geblokkeerd',
    'Start Playback': 'Start afspelen',
    'Subtitles': 'Ondertiteling',
    'Suspended': 'Onderbroken',
    'This video is playing in Picture in Picture': 'Deze video wordt beeld in beeld afgespeeld',
    'Unmute': 'Geluid aan',
    'Video Playback': 'Video afspelen',
    'Video Playback Placeholder': 'Plaatsaanduiding voor afspelen video',
    'Volume': 'Volume',
    'Waiting': 'Wachten'
};