var UIStringTable = {
    '##WIRELESS_PLAYBACK_DEVICE_TYPE##': 'AirPlay',
    '##WIRELESS_PLAYBACK_DEVICE_NAME##': 'Video này đang phát trên “##DEVICE_NAME##”.',

    '##TVOUT_DEVICE_TYPE##': 'Đã kết nối TV',
    '##TVOUT_DEVICE_NAME##': 'Video này đang phát trên TV.',

    'Aborted': 'Đã hủy',
    'Audio': 'Âm thanh',
    'Audio Playback': 'Phát lại Âm thanh',
    'Captions': 'Chú thích',
    'Choose Wireless Display': 'Chọn Màn hình Không dây',
    'Display Full Screen': 'Hiển thị Toàn Màn hình',
    'Display Picture in Picture': 'Hiển thị Hình trong Hình',
    'Duration': 'Thời lượng',
    'Elapsed': 'Đã qua',
    'Error': 'Lỗi',
    'Exit Full Screen': 'Thoát Toàn Màn hình',
    'Fast Forward': 'Tua đi Nhanh',
    'Live Broadcast': 'Phát Trực tiếp',
    'Loading': 'Đang tải',
    'Maximum Volume': 'Âm lượng Tối đa',
    'Minimum Volume': 'Âm lượng Tối thiểu',
    'Mute': 'Tắt tiếng',
    'Pause': 'Tạm dừng',
    'Play': 'Phát',
    'Remaining': 'Còn lại',
    'Rewind': 'Tua lại',
    'Rewind ##sec## Seconds': 'Tua lại ##sec## Giây',
    'Show Controls': 'Hiển thị Điều khiển',
    'Stalled': 'Đã dừng',
    'Start Playback': 'Bắt đầu Phát lại',
    'Subtitles': 'Phụ đề',
    'Suspended': 'Treo',
    'This video is playing in Picture in Picture': 'Video đang phát ở chế độ Hình trong Hình',
    'Unmute': 'Bật tiếng',
    'Video Playback': 'Phát lại Video',
    'Video Playback Placeholder': 'Trình giữ chỗ Phát lại Video',
    'Volume': 'Âm lượng',
    'Waiting': 'Đang chờ'
};