var UIStringTable = {
    '##WIRELESS_PLAYBACK_DEVICE_TYPE##': 'AirPlay',
    '##WIRELESS_PLAYBACK_DEVICE_NAME##': 'Video ini sedang bermain di “##DEVICE_NAME##”.',

    '##TVOUT_DEVICE_TYPE##': 'TV Disambung',
    '##TVOUT_DEVICE_NAME##': 'Video ini sedang bermain di TV.',

    'Aborted': 'Dihenti Paksa',
    'Audio': 'Audio',
    'Audio Playback': 'Main Balik Audio',
    'Captions': 'Kapsyen',
    'Choose Wireless Display': 'Pilih Paparan Wayarles',
    'Display Full Screen': 'Paparkan Skrin Penuh',
    'Display Picture in Picture': 'Paparkan Gambar dalam Gambar',
    'Duration': 'Tempoh',
    'Elapsed': 'Berlalu',
    'Error': 'Ralat',
    'Exit Full Screen': 'Keluar Skrin Penuh',
    'Fast Forward': 'Maju Pantas',
    'Live Broadcast': 'Siaran Langsung',
    'Loading': 'Memuatkan',
    'Maximum Volume': 'Kelantangan Maksimum',
    'Minimum Volume': 'Kelantangan Minimum',
    'Mute': 'Senyap',
    'Pause': 'Jeda',
    'Play': 'Main',
    'Remaining': 'Tinggal',
    'Rewind': 'Putar Balik',
    'Rewind ##sec## Seconds': 'Putar Balik ##sec## Saat',
    'Show Controls': 'Tunjukkan Kawalan',
    'Stalled': 'Tergendala',
    'Start Playback': 'Mulakan Main Balik',
    'Subtitles': 'Sari Kata',
    'Suspended': 'Digantung',
    'This video is playing in Picture in Picture': 'Video ini dimainkan dalam Gambar dalam Gambar',
    'Unmute': 'Nyahbisu',
    'Video Playback': 'Main Balik Video',
    'Video Playback Placeholder': 'Ruang Letak Main Balik Video',
    'Volume': 'Kelantangan',
    'Waiting': 'Menunggu'
};