var UIStringTable = {
    '##WIRELESS_PLAYBACK_DEVICE_TYPE##': 'AirPlay',
    '##WIRELESS_PLAYBACK_DEVICE_NAME##': 'Este vídeo está a ser reproduzido no “##DEVICE_NAME##”.',

    '##TVOUT_DEVICE_TYPE##': 'Ligado a um televisor',
    '##TVOUT_DEVICE_NAME##': 'Este vídeo está a ser reproduzido no televisor.',

    'Aborted': 'Cancelado',
    'Audio': 'Áudio',
    'Audio Playback': 'Reprodução de áudio',
    'Captions': 'Legendas',
    'Choose Wireless Display': 'Escolher monitor sem fios',
    'Display Full Screen': 'Ver em ecrã completo',
    'Display Picture in Picture': 'Apresentar Picture in Picture',
    'Duration': 'Duração',
    'Elapsed': 'Decorrido',
    'Error': 'Erro',
    'Exit Full Screen': 'Sair do ecrã completo',
    'Fast Forward': 'Avançar rápido',
    'Live Broadcast': 'Difusão ao vivo',
    'Loading': 'A carregar',
    'Maximum Volume': 'Volume máximo',
    'Minimum Volume': 'Volume mínimo',
    'Mute': 'Tirar o som',
    'Pause': 'Pausa',
    'Play': 'Reproduzir',
    'Remaining': 'Falta',
    'Rewind': 'Rebobinar',
    'Rewind ##sec## Seconds': 'Rebobinar ##sec## segundos',
    'Show Controls': 'Mostrar controlos',
    'Stalled': 'Interrompido',
    'Start Playback': 'Iniciar reprodução',
    'Subtitles': 'Legendas',
    'Suspended': 'Suspenso',
    'This video is playing in Picture in Picture': 'Este vídeo está a ser reproduzido em Picture in Picture',
    'Unmute': 'Ligar o som',
    'Video Playback': 'Reprodução de vídeo',
    'Video Playback Placeholder': 'Marcador de posição de reprodução de vídeo',
    'Volume': 'Volume',
    'Waiting': 'A aguardar'
};