var UIStringTable = {
    '##WIRELESS_PLAYBACK_DEVICE_TYPE##': 'AirPlay',
    '##WIRELESS_PLAYBACK_DEVICE_NAME##': 'Acest clip video este în redare pe “##DEVICE_NAME##”.',

    '##TVOUT_DEVICE_TYPE##': 'TV conectat',
    '##TVOUT_DEVICE_NAME##': 'Acest clip video este în redare pe TV.',

    'Aborted': 'Abandonată',
    'Audio': 'Audio',
    'Audio Playback': 'Redare audio',
    'Captions': 'Legende',
    'Choose Wireless Display': 'Alegeți afișajul wireless',
    'Display Full Screen': 'Afișare pe tot ecranul',
    'Display Picture in Picture': 'Afișați Imagine în imagine',
    'Duration': 'Durată',
    'Elapsed': 'Timp scurs',
    'Error': 'Eroare',
    'Exit Full Screen': 'Opriți afișarea pe tot ecranul',
    'Fast Forward': 'Repede înainte',
    'Live Broadcast': 'Difuzare live',
    'Loading': 'Încărcare',
    'Maximum Volume': 'Volum maxim',
    'Minimum Volume': 'Volum minim',
    'Mute': 'Activați modul mut',
    'Pause': 'Suspendați',
    'Play': 'Redați',
    'Remaining': 'Timp rămas',
    'Rewind': 'Derulare înapoi',
    'Rewind ##sec## Seconds': 'Derulare înapoi ##sec## secunde',
    'Show Controls': 'Afișați comenzile',
    'Stalled': 'Blocată',
    'Start Playback': 'Porniți redarea',
    'Subtitles': 'Subtitrări',
    'Suspended': 'Suspendată',
    'This video is playing in Picture in Picture': 'Acest clip video este redat în modul Imagine în imagine',
    'Unmute': 'Dezactivați modul mut',
    'Video Playback': 'Redare video',
    'Video Playback Placeholder': 'Substituent redare video',
    'Volume': 'Volum',
    'Waiting': 'Așteptare'
};