var UIStringTable = {
    '##WIRELESS_PLAYBACK_DEVICE_TYPE##': 'AirPlay',
    '##WIRELESS_PLAYBACK_DEVICE_NAME##': 'Bu video “##DEVICE_NAME##” üzerinde oynatılıyor.',

    '##TVOUT_DEVICE_TYPE##': 'TV Bağlı',
    '##TVOUT_DEVICE_NAME##': 'Bu video TV\'de oynatılıyor.',

    'Aborted': 'Durduruldu',
    'Audio': 'Ses',
    'Audio Playback': 'Ses Çalma',
    'Captions': 'Altyazılar',
    'Choose Wireless Display': 'Kablosuz Ekranı Seçin',
    'Display Full Screen': 'Tam Ekran Görüntüle',
    'Display Picture in Picture': 'Resim İçinde Resim Görüntüle',
    'Duration': 'Süre',
    'Elapsed': 'Geçen',
    'Error': 'Hata',
    'Exit Full Screen': 'Tam Ekrandan Çık',
    'Fast Forward': 'Hızlı İleri',
    'Live Broadcast': 'Canlı Yayın',
    'Loading': 'Yükleniyor',
    'Maximum Volume': 'Maksimum Ses Yüksekliği',
    'Minimum Volume': 'Minimum Ses Yüksekliği',
    'Mute': 'Sesi Kapat',
    'Pause': 'Duraklat',
    'Play': 'Oynat',
    'Remaining': 'Kalan',
    'Rewind': 'Geri Sar',
    'Rewind ##sec## Seconds': '##sec## Saniye Geri Sar',
    'Show Controls': 'Denetimleri Göster',
    'Stalled': 'Durdu',
    'Start Playback': 'Oynatımı Başlat',
    'Subtitles': 'Altyazılar',
    'Suspended': 'Beklemede',
    'This video is playing in Picture in Picture': 'Bu video Resim İçinde Resim olarak oynatılıyor',
    'Unmute': 'Sesi Aç',
    'Video Playback': 'Video Oynatımı',
    'Video Playback Placeholder': 'Video Oynatımı Yer Tutucu',
    'Volume': 'Ses Yüksekliği',
    'Waiting': 'Bekliyor'
};