var UIStringTable = {
    '##WIRELESS_PLAYBACK_DEVICE_TYPE##': 'AirPlay',
    '##WIRELESS_PLAYBACK_DEVICE_NAME##': 'このビデオは“##DEVICE_NAME##”で再生中です。',

    '##TVOUT_DEVICE_TYPE##': 'テレビに接続しました',
    '##TVOUT_DEVICE_NAME##': 'このビデオはテレビで再生中です。',

    'Aborted': '中断しました',
    'Audio': 'オーディオ',
    'Audio Playback': 'オーディオ再生',
    'Captions': 'キャプション',
    'Choose Wireless Display': 'ワイヤレスディスプレイを選択',
    'Display Full Screen': 'フルスクリーンで表示',
    'Display Picture in Picture': 'ピクチャ・イン・ピクチャを表示',
    'Duration': '継続時間',
    'Elapsed': '経過',
    'Error': 'エラー',
    'Exit Full Screen': 'フルスクリーンを解除',
    'Fast Forward': '早送り',
    'Live Broadcast': 'ライブブロードキャスト',
    'Loading': '読み込み中',
    'Maximum Volume': '最大音量',
    'Minimum Volume': '最小音量',
    'Mute': '消音',
    'Pause': '一時停止',
    'Play': '再生',
    'Remaining': '残り',
    'Rewind': '巻き戻し',
    'Rewind ##sec## Seconds': '##sec##秒巻き戻す',
    'Show Controls': 'コントロールを表示',
    'Stalled': '停止',
    'Start Playback': '再生を停止',
    'Subtitles': '字幕',
    'Suspended': '中断',
    'This video is playing in Picture in Picture': 'このビデオはピクチャ・イン・ピクチャで再生中です',
    'Unmute': '消音を解除',
    'Video Playback': 'ビデオ再生',
    'Video Playback Placeholder': 'ビデオ再生プレースホルダ',
    'Volume': '音量',
    'Waiting': '待機中'
};