var UIStringTable = {
    '##WIRELESS_PLAYBACK_DEVICE_TYPE##': 'AirPlay',
    '##WIRELESS_PLAYBACK_DEVICE_NAME##': 'Dieses Video spielt auf „##DEVICE_NAME##“.',

    '##TVOUT_DEVICE_TYPE##': 'TV angeschlossen',
    '##TVOUT_DEVICE_NAME##': 'Das Video spielt auf dem TV.',

    'Aborted': 'Abgebrochen',
    'Audio': 'Audio',
    'Audio Playback': 'Audiowiedergabe',
    'Captions': 'Untertitel',
    'Choose Wireless Display': 'Drahtloses Display wählen',
    'Display Full Screen': 'Bildschirmfüllend anzeigen',
    'Display Picture in Picture': 'Bild-in-Bild anzeigen',
    'Duration': 'Dauer',
    'Elapsed': 'Verstrichen',
    'Error': 'Fehler',
    'Exit Full Screen': 'Vollbild aus',
    'Fast Forward': 'Schneller Vorlauf',
    'Live Broadcast': 'Liveübertragung',
    'Loading': 'Laden …',
    'Maximum Volume': 'Maximale Lautstärke',
    'Minimum Volume': 'Minimale Lautstärke',
    'Mute': 'Stumm',
    'Pause': 'Pause',
    'Play': 'Wiedergeben',
    'Remaining': 'Verbleibend',
    'Rewind': 'Zurückspulen',
    'Rewind ##sec## Seconds': '##sec## Sekunden zurück',
    'Show Controls': 'Steuerung einblenden',
    'Stalled': 'Unterbrochen',
    'Start Playback': 'Wiedergabe starten',
    'Subtitles': 'Untertitel',
    'Suspended': 'Angehalten',
    'This video is playing in Picture in Picture': 'Dieses Video wird Bild-in-Bild wiedergegeben',
    'Unmute': 'Ton an',
    'Video Playback': 'Videowiedergabe',
    'Video Playback Placeholder': 'Platzhalter für Videowiedergabe',
    'Volume': 'Lautstärke',
    'Waiting': 'Warten'
};