var UIStringTable = {
    '##WIRELESS_PLAYBACK_DEVICE_TYPE##': 'AirPlay',
    '##WIRELESS_PLAYBACK_DEVICE_NAME##': 'הסרט מוקרן כעת ב״##DEVICE_NAME##״.',

    '##TVOUT_DEVICE_TYPE##': 'הטלוויזיה מחוברת',
    '##TVOUT_DEVICE_NAME##': 'סרט זה מתנגן כעת בטלוויזיה.',

    'Aborted': 'בוטל',
    'Audio': 'אודיו',
    'Audio Playback': 'השמעת אודיו',
    'Captions': 'כתוביות',
    'Choose Wireless Display': 'בחר/י צג אלחוטי',
    'Display Full Screen': 'הצג במסך מלא',
    'Display Picture in Picture': 'הצג ״תמונה בתוך תמונה״',
    'Duration': 'אורך',
    'Elapsed': 'זמן שחלף',
    'Error': 'שגיאה',
    'Exit Full Screen': 'צא ממסך מלא',
    'Fast Forward': 'הרץ קדימה',
    'Live Broadcast': 'שידור חי',
    'Loading': 'טוען',
    'Maximum Volume': 'עוצמה מירבית',
    'Minimum Volume': 'עוצמה מזערית',
    'Mute': 'השתק',
    'Pause': 'השהה',
    'Play': 'נגן',
    'Remaining': 'נותרו',
    'Rewind': 'הרץ אחורה',
    'Rewind ##sec## Seconds': 'הרץ ##sec## שניות אחורה',
    'Show Controls': 'הצג פקדים',
    'Stalled': 'תקוע',
    'Start Playback': 'הפעל',
    'Subtitles': 'כתוביות',
    'Suspended': 'מושעה',
    'This video is playing in Picture in Picture': 'סרט זה מתנגן במצב ״תמונה בתוך תמונה״',
    'Unmute': 'בטל השתקה',
    'Video Playback': 'הפעלת וידאו',
    'Video Playback Placeholder': 'מציין מיקום של הפעלת וידאו',
    'Volume': 'עוצמת שמע',
    'Waiting': 'ממתין'
};