var UIStringTable = {
    '##WIRELESS_PLAYBACK_DEVICE_TYPE##': 'AirPlay',
    '##WIRELESS_PLAYBACK_DEVICE_NAME##': 'Este video se está reproduciendo en “##DEVICE_NAME##”.',

    '##TVOUT_DEVICE_TYPE##': 'Televisión conectada',
    '##TVOUT_DEVICE_NAME##': 'El video se está reproduciendo en la televisión.',

    'Aborted': 'Abortado',
    'Audio': 'Audio',
    'Audio Playback': 'Reproducción de audio',
    'Captions': 'Subtítulos',
    'Choose Wireless Display': 'Elegir pantalla inalámbrica',
    'Display Full Screen': 'Mostrar pantalla completa',
    'Display Picture in Picture': 'Mostrar imagen dentro de otra (PIP)',
    'Duration': 'Duración',
    'Elapsed': 'Transcurrido',
    'Error': 'Error',
    'Exit Full Screen': 'Salir de pantalla completa',
    'Fast Forward': 'Avance rápido',
    'Live Broadcast': 'Transmisión en vivo',
    'Loading': 'Cargando',
    'Maximum Volume': 'Volumen máximo',
    'Minimum Volume': 'Volumen mínimo',
    'Mute': 'Silenciar',
    'Pause': 'Pausar',
    'Play': 'Reproducir',
    'Remaining': 'Restante',
    'Rewind': 'Retroceder',
    'Rewind ##sec## Seconds': 'Retroceder ##sec## segundos',
    'Show Controls': 'Mostrar controles',
    'Stalled': 'Retrasado',
    'Start Playback': 'Iniciar reproducción',
    'Subtitles': 'Subtítulos',
    'Suspended': 'Suspendido',
    'This video is playing in Picture in Picture': 'Video reproduciéndose en imagen dentro de otra (PIP)',
    'Unmute': 'Activar sonido',
    'Video Playback': 'Reproducción de video',
    'Video Playback Placeholder': 'Marcador de posición de reproducción de video',
    'Volume': 'Volumen',
    'Waiting': 'Esperando'
};