var UIStringTable = {
    '##WIRELESS_PLAYBACK_DEVICE_TYPE##': 'AirPlay',
    '##WIRELESS_PLAYBACK_DEVICE_NAME##': 'Riproduzione video su “##DEVICE_NAME##”.',

    '##TVOUT_DEVICE_TYPE##': 'TV connesso',
    '##TVOUT_DEVICE_NAME##': 'Riproduzione video sulla TV.',

    'Aborted': 'Interrotto',
    'Audio': 'Audio',
    'Audio Playback': 'Riproduzione audio',
    'Captions': 'Sottot. non udenti',
    'Choose Wireless Display': 'Scegli monitor wireless',
    'Display Full Screen': 'Visualizza a tutto schermo',
    'Display Picture in Picture': 'Schermo PIP',
    'Duration': 'Durata',
    'Elapsed': 'Trascorso',
    'Error': 'Errore',
    'Exit Full Screen': 'Disattiva modalità a tutto schermo',
    'Fast Forward': 'Avanti veloce',
    'Live Broadcast': 'Trasmissione in diretta',
    'Loading': 'Carico',
    'Maximum Volume': 'Volume massimo',
    'Minimum Volume': 'Volume minimo',
    'Mute': 'Disattiva audio',
    'Pause': 'Pausa',
    'Play': 'Riproduci',
    'Remaining': 'Rimanente',
    'Rewind': 'Riavvolgi',
    'Rewind ##sec## Seconds': 'Riavvolgi ##sec## secondi',
    'Show Controls': 'Mostra controlli',
    'Stalled': 'Bloccato',
    'Start Playback': 'Avvia riproduzione',
    'Subtitles': 'Sottotitoli',
    'Suspended': 'Sospeso',
    'This video is playing in Picture in Picture': 'Questo video viene riprodotto in modalità PIP',
    'Unmute': 'Attiva audio',
    'Video Playback': 'Riproduzione video',
    'Video Playback Placeholder': 'Segnaposto riproduzione video',
    'Volume': 'Volume',
    'Waiting': 'In attesa'
};