var UIStringTable = {
    '##WIRELESS_PLAYBACK_DEVICE_TYPE##': 'AirPlay',
    '##WIRELESS_PLAYBACK_DEVICE_NAME##': 'Αυτό το βίντεο αναπαράγεται στο «##DEVICE_NAME##».',

    '##TVOUT_DEVICE_TYPE##': 'Τηλεόραση συνδεδεμένη',
    '##TVOUT_DEVICE_NAME##': 'Αυτό το βίντεο αναπαράγεται στην τηλεόραση.',

    'Aborted': 'Ματαιώθηκε',
    'Audio': 'Ήχος',
    'Audio Playback': 'Αναπαραγωγή ήχου',
    'Captions': 'Λεζάντες',
    'Choose Wireless Display': 'Επιλογή ασύρματης οθόνης',
    'Display Full Screen': 'Εμφάνιση σε πλήρη οθόνη',
    'Display Picture in Picture': 'Εμφάνιση εικόνας εντός εικόνας',
    'Duration': 'Διάρκεια',
    'Elapsed': 'Παρήλθε',
    'Error': 'Σφάλμα',
    'Exit Full Screen': 'Έξοδος από πλήρη οθόνη',
    'Fast Forward': 'Γρήγορη προώθηση',
    'Live Broadcast': 'Ζωντανή αναμετάδοση',
    'Loading': 'Φόρτωση…',
    'Maximum Volume': 'Μέγιστη ένταση ήχου',
    'Minimum Volume': 'Ελάχιστη ένταση ήχου',
    'Mute': 'Σίγαση',
    'Pause': 'Παύση',
    'Play': 'Αναπαραγωγή',
    'Remaining': 'Απομένουν',
    'Rewind': 'Γρήγορη επαναφορά',
    'Rewind ##sec## Seconds': 'Γρήγορη επαναφορά για ##sec## δευτερόλεπτα',
    'Show Controls': 'Εμφάνιση χειριστηρίων',
    'Stalled': 'Καθυστέρησε',
    'Start Playback': 'Έναρξη αναπαραγωγής',
    'Subtitles': 'Υπότιτλοι',
    'Suspended': 'Σε αναστολή',
    'This video is playing in Picture in Picture': 'Αυτό το βίντεο αναπαράγεται σε Εικόνα εντός εικόνας',
    'Unmute': 'Αποσίγαση',
    'Video Playback': 'Αναπαραγωγή βίντεο',
    'Video Playback Placeholder': 'Δεσμευτικό θέσης αναπαραγωγής βίντεο',
    'Volume': 'Ένταση ήχου',
    'Waiting': 'Σε αναμονή'
};